(function(){
  const stream=document.querySelector('#chatStream'),form=document.querySelector('#chatForm'),input=document.querySelector('#chatInput');
  if(!stream||!form)return;
  const agents={tutor:{name:'NORA · TUTOR DIDATTICO',icon:'🧭'},exercise:{name:'LEO · GENERATORE ESERCIZI',icon:'🧩'},corrector:{name:'MIA · CORRETTORE',icon:'✓'},safety:{name:'ARIA · CONTROLLO SICUREZZA',icon:'🛡️'},analyst:{name:'ELIO · ANALISTA PROGRESSI',icon:'📈'}};
  const privateData=[/\b\d{3}[ .-]?\d{3}[ .-]?\d{4}\b/,/[\w.+-]+@[\w.-]+\.[a-z]{2,}/i,/\bmi chiamo\b/i,/\babito (a|in|al|in via)\b/i,/\bla mia scuola\b/i,/\bpassword\b/i];
  const harmful=[/come (posso )?(fare|costruire).*(bomba|arma)/i,/far(e)? male/i,/suicid/i];
  const escapeHtml=v=>v.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  function activate(id){document.querySelectorAll('.agent-row').forEach(r=>r.classList.toggle('active',r.dataset.agent===id));document.querySelector('#routeMessage').textContent=`Richiesta affidata a ${agents[id].name.split(' · ')[0].toLowerCase()}.`}
  function message(type,html,id){const el=document.createElement('div');el.className=`chat-message ${type}`;if(type==='user')el.innerHTML=`<span>Tu</span><div><p>${escapeHtml(html)}</p></div>`;else{const a=agents[id];el.innerHTML=`<span>${a.icon}</span><div><small>${a.name}</small><p>${html}</p></div>`}stream.appendChild(el);stream.scrollTop=stream.scrollHeight;return el}
  function route(t){if(privateData.some(p=>p.test(t))||harmful.some(p=>p.test(t)))return'safety';if(/esercizio|quiz|domand|allen|sfida/i.test(t))return'exercise';if(/corregg|controlla|mia risposta|ho scritto/i.test(t))return'corrector';if(/progress|miglior|come sto andando|risultati/i.test(t))return'analyst';return'tutor'}
  function topic(t){if(/frazion/i.test(t))return'frazioni';if(/verb|grammatic/i.test(t))return'verbi';if(/roma|roman|storia/i.test(t))return'storia';if(/vulcan|scienz|pianet/i.test(t))return'scienze';if(/geometr|matematic|equaz/i.test(t))return'matematica';return'uso dell’AI'}
  function tutor(t){const x=topic(t),level=document.querySelector('#schoolLevel').value;if(x==='frazioni')return level==='primaria'?'Immagina due pizze uguali: una divisa in 2 parti e una in 4. Quanti quarti devi prendere per avere la stessa quantità di <b>1/2</b>? Prova tu prima del prossimo indizio.':'Moltiplicando numeratore e denominatore per lo stesso numero, il valore non cambia. Quale numero trasforma <b>2/3</b> in <b>?/12</b>?';if(x==='verbi')return 'Nella frase <b>“Domani Luca correrà al parco”</b>, quale parola indica l’azione? L’azione è nel passato, presente o futuro?';if(x==='storia')return 'Per capire un evento storico usiamo tre domande: <b>quando, dove e perché</b>. Quale vuoi ricostruire per prima?';if(x==='scienze')return 'Osserviamo causa ed effetto: che cosa pensi possa accadere quando la pressione sotto un vulcano aumenta? Scrivi la tua ipotesi.';return `Ho capito che vuoi lavorare su <b>${x}</b>. Qual è il punto preciso che ti sembra più difficile?`}
  function exercise(t){const x=topic(t),bank={frazioni:['Quale frazione equivale a 1/2?',['2/4','2/3','3/5'],0,'2/4 si semplifica dividendo entrambi i numeri per 2.'],verbi:['Qual è il verbo nella frase “Sara legge un libro”?',['Sara','legge','libro'],1,'“Legge” indica l’azione compiuta da Sara.'],storia:['In quale anno, secondo la tradizione, fu fondata Roma?',['753 a.C.','476 d.C.','1492'],0,'La data tradizionale della fondazione di Roma è il 753 a.C.'],scienze:['Quale pianeta è più vicino al Sole?',['Terra','Marte','Mercurio'],2,'Mercurio è il primo pianeta del Sistema Solare.'],matematica:['Quanto vale 3 × (4 + 2)?',['18','14','24'],0,'Prima si calcola la parentesi e poi la moltiplicazione.'],'uso dell’AI':['Quale richiesta aiuta di più un tutor?',['Spiegami tutto','Spiegami le frazioni con un esempio per la prima media','Fammi il compito'],1,'Contiene argomento, formato e livello.']},e=bank[x];return `<b>Mini-sfida su ${x}</b><br>${e[0]}<span class="inline-answers">${e[1].map((a,i)=>`<button data-ex-answer="${i}" data-correct="${e[2]}" data-why="${escapeHtml(e[3])}">${a}</button>`).join('')}</span>`}
  function correct(t){if(/753\s*a\.?c/i.test(t))return 'La risposta è <b>corretta</b>. Per migliorarla, aggiungi che si tratta di una data tradizionale legata al racconto di Romolo e Remo.';if(/=/.test(t))return 'Controlla due cose: hai rispettato l’ordine delle operazioni? Hai verificato il risultato con il calcolo inverso?';return 'Scrivi separatamente la consegna e ciò che hai risposto: <b>“Domanda: … / La mia risposta: …”</b>. Così potrò aiutarti senza svolgere il compito al posto tuo.'}
  function analyst(){const s={xp:120,missions:2,...JSON.parse(localStorage.getItem('imparaia-progress')||'{}')};return `Hai raccolto <b>${s.xp} XP</b> e completato <b>${s.missions} missioni</b>. Il prossimo obiettivo consigliato è allenare la verifica delle fonti.`}
  function safe(t){if(harmful.some(p=>p.test(t)))return 'Non posso aiutarti a creare qualcosa che possa ferire te o altre persone. Se ti senti in pericolo o pensi di farti male, parlane subito con un adulto di fiducia o chiama il <b>112</b>.';return 'Ho notato un possibile dato personale. Non scrivere nome completo, indirizzo, scuola, telefono, email o password. Riformula senza queste informazioni.'}
  function reply(id,t){return id==='tutor'?tutor(t):id==='exercise'?exercise(t):id==='corrector'?correct(t):id==='analyst'?analyst():safe(t)}
  function submit(text){const t=text.trim();if(!t)return;message('user',t);input.value='';const id=route(t);document.querySelector('#routeMessage').textContent='Orione sta analizzando la richiesta…';document.querySelectorAll('.agent-row').forEach(r=>r.classList.remove('active'));const wait=message('ai','<span class="thinking"><i></i><i></i><i></i></span>','tutor');setTimeout(()=>{wait.remove();activate(id);message(id==='safety'?'safety':'ai',reply(id,t),id);if(id!=='safety')localStorage.setItem('imparaia-interactions',String(Number(localStorage.getItem('imparaia-interactions')||0)+1))},650)}
  form.addEventListener('submit',e=>{e.preventDefault();submit(input.value)});document.querySelectorAll('[data-quick]').forEach(b=>b.addEventListener('click',()=>submit(b.dataset.quick)));
  document.querySelector('#clearChat').addEventListener('click',()=>{stream.innerHTML='<div class="chat-message ai"><span>✦</span><div><small>ORIONE · COORDINATORE</small><p>Conversazione azzerata. Che cosa vuoi imparare?</p></div></div>';document.querySelectorAll('.agent-row').forEach(r=>r.classList.remove('active'));document.querySelector('#routeMessage').textContent='Pronto a scegliere l’agente più adatto.'});
  stream.addEventListener('click',e=>{const b=e.target.closest('[data-ex-answer]');if(!b||b.disabled)return;const box=b.closest('.inline-answers');box.querySelectorAll('button').forEach(x=>x.disabled=true);const ok=b.dataset.exAnswer===b.dataset.correct;b.classList.add(ok?'answer-ok':'answer-no');box.children[Number(b.dataset.correct)].classList.add('answer-ok');message('ai',`${ok?'<b>Esatto!</b>':'<b>Quasi!</b>'} ${b.dataset.why}`,'corrector');activate('corrector');if(ok){const s={xp:120,missions:2,streak:4,...JSON.parse(localStorage.getItem('imparaia-progress')||'{}')};s.xp+=10;localStorage.setItem('imparaia-progress',JSON.stringify(s));document.querySelector('#xpTop').textContent=s.xp;document.querySelector('#xpStat').textContent=s.xp}});
  document.querySelector('#goRecommended').addEventListener('click',()=>document.querySelector('[data-view="home"]').click());
})();
