const defaults={xp:120,missions:2,streak:4,missionDone:false};
let state={...defaults,...JSON.parse(localStorage.getItem('imparaia-progress')||'{}')};
const $=(s,root=document)=>root.querySelector(s);const $$=(s,root=document)=>[...root.querySelectorAll(s)];
function save(){localStorage.setItem('imparaia-progress',JSON.stringify(state));renderStats()}
function renderStats(){['xpTop','xpStat'].forEach(id=>$('#'+id).textContent=state.xp);$('#missionsStat').textContent=state.missions;$('#streakDays').textContent=$('#streakStat').textContent=state.streak;if(state.missionDone){$('#startMission').textContent='Missione completata ✓';$('#startMission').disabled=true;$('#pathPercent').textContent='60%';$('#pathBar').style.width='60%'}}
function toast(text){const el=$('#toast');el.textContent=text;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2400)}
$$('.nav-btn').forEach(btn=>btn.addEventListener('click',()=>{const id=btn.dataset.view;$$('.nav-btn,.view').forEach(el=>el.classList.remove('active'));btn.classList.add('active');$('#'+id).classList.add('active');window.scrollTo({top:0,behavior:'smooth'})}));
const modal=$('#missionModal');let missionIndex=0;
const questions=[
  {title:'Quale frase ti sembra sospetta?',text:'Un’AI dice: “I polpi hanno cinque cuori.” Che cosa fai?',answers:['La copio subito nei compiti','La verifico su una fonte affidabile','È scritta bene, quindi è vera'],correct:1,feedback:'Ottima scelta! I polpi hanno tre cuori, non cinque. Una frase sicura può comunque essere sbagliata.'},
  {title:'Qual è la fonte migliore?',text:'Devi verificare quanti pianeti ci sono nel Sistema Solare. Dove cerchi?',answers:['Un commento anonimo','Un sito scientifico o un libro scolastico','Chiedo alla stessa AI di ripeterlo'],correct:1,feedback:'Esatto. Per una verifica scegli fonti riconoscibili, aggiornate e adatte all’argomento.'},
  {title:'La regola del detective',text:'Cosa puoi chiedere all’AI quando risponde?',answers:['Di parlare più velocemente','Di indicare le fonti da controllare','Di non sbagliare mai'],correct:1,feedback:'Giusto! Chiedere le fonti è un buon inizio, ma dovrai comunque aprirle e controllarle.'}
];
function openMission(){missionIndex=0;modal.hidden=false;document.body.style.overflow='hidden';renderQuestion();$('.close-btn').focus()}
function closeMission(){modal.hidden=true;document.body.style.overflow='';$('#startMission').focus()}
function renderQuestion(){const q=questions[missionIndex];$('#missionStep').innerHTML=`<p class="eyebrow">SFIDA ${missionIndex+1} DI ${questions.length}</p><h2 class="question-title">${q.title}</h2><p>${q.text}</p><div class="answers">${q.answers.map((a,i)=>`<button class="answer-btn" data-answer="${i}">${a}</button>`).join('')}</div><div class="feedback" hidden></div>`;$$('[data-answer]',modal).forEach(b=>b.addEventListener('click',()=>answer(Number(b.dataset.answer))))}
function answer(i){const q=questions[missionIndex],buttons=$$('.answer-btn',modal),feedback=$('.feedback',modal);buttons.forEach(b=>b.disabled=true);buttons[q.correct].classList.add('correct');if(i!==q.correct)buttons[i].classList.add('wrong');feedback.hidden=false;feedback.innerHTML=`<strong>${i===q.correct?'Perfetto!':'Ci sei quasi.'}</strong><br>${q.feedback}<br><button class="primary-btn" id="nextQuestion" style="margin-top:.8rem">${missionIndex<questions.length-1?'Prossima sfida':'Vedi il risultato'}</button>`;$('#nextQuestion').addEventListener('click',()=>{missionIndex++;missionIndex<questions.length?renderQuestion():completeMission()})}
function completeMission(){if(!state.missionDone){state.xp+=80;state.missions+=1;state.missionDone=true;save()}$('#missionStep').innerHTML='<div class="success-screen"><div class="success-icon">✓</div><p class="eyebrow" style="margin-top:1rem">MISSIONE COMPIUTA</p><h2 class="question-title" style="margin-right:0">Sei un vero detective!</h2><p>Hai imparato che l’AI può sbagliare e che una risposta va controllata. Hai guadagnato <b>80 XP</b>.</p><button class="primary-btn" data-close="true">Torna alle missioni</button></div>';$$('[data-close]',modal).forEach(x=>x.addEventListener('click',closeMission))}
$('#startMission').addEventListener('click',openMission);modal.addEventListener('click',e=>{if(e.target.dataset.close)closeMission()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!modal.hidden)closeMission()});
const promptInput=$('#promptInput');promptInput.addEventListener('input',()=>$('#charCount').textContent=`${promptInput.value.length} / 300`);
$$('[data-prompt]').forEach(b=>b.addEventListener('click',()=>{promptInput.value=b.dataset.prompt;promptInput.dispatchEvent(new Event('input'));promptInput.focus()}));
$('#analyzePrompt').addEventListener('click',()=>{const t=promptInput.value.trim();if(t.length<5){toast('Scrivi prima una richiesta un po’ più completa.');return}const tests={topic:t.split(/\s+/).length>=3,goal:/spiega|aiuta|crea|fammi|scrivi|confronta|riassumi|parlami/i.test(t),format:/punti|tabella|quiz|domande|parole|elenco|storia|dialogo/i.test(t),level:/elementare|media|anni|classe|semplice|facile|ragazz/i.test(t)};Object.entries(tests).forEach(([k,v])=>$(`[data-check="${k}"]`).classList.toggle('pass',v));const missing=Object.entries(tests).filter(([,v])=>!v).map(([k])=>({topic:'l’argomento',goal:'cosa vuoi ottenere',format:'il formato della risposta',level:'il livello di difficoltà'}[k]));const score=Object.values(tests).filter(Boolean).length;if(score===4){$('#coachMessage').innerHTML='<b>Prompt eccellente!</b> È chiaro, specifico e adatto al tuo livello. Ricorda comunque di controllare le informazioni ricevute.';if(!localStorage.getItem('imparaia-prompt-bonus')){state.xp+=30;save();localStorage.setItem('imparaia-prompt-bonus','1');toast('+30 XP: primo prompt completo!')}}else{$('#coachMessage').innerHTML=`Buon inizio! Per renderlo ancora migliore aggiungi <b>${missing.join('</b> e <b>')}</b>.`}});
$$('.lesson-card:not(.locked)').forEach(b=>b.addEventListener('click',()=>toast(b.classList.contains('complete')?'Questa missione è già completata.':'Completa prima la missione di oggi.')));
$('#resetProgress').addEventListener('click',()=>{if(confirm('Vuoi davvero azzerare tutti i progressi di prova?')){localStorage.removeItem('imparaia-progress');localStorage.removeItem('imparaia-prompt-bonus');state={...defaults};location.reload()}});
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));
renderStats();
